name: Frontend Lint (Super Linter)

on:
  push:
    branches: [ "development" ]
  workflow_dispatch:

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Super Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: development
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_ALL_CODEBASE: false

          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_TSX: true
